/**
 * Canopy — Blog Data
 * Static blog posts with full content. In production these could come from
 * Firestore or a CMS, but static data keeps deployment simple.
 */

export interface BlogPost {
  slug: string
  title: string
  excerpt: string
  content: string
  author: {
    name: string
    role: string
    avatar: string // emoji initials
  }
  category: string
  readTime: number // minutes
  publishedAt: string // ISO date
  coverEmoji: string
  tags: string[]
}

export const BLOG_POSTS: BlogPost[] = [
  {
    slug: "understanding-your-carbon-footprint",
    title: "Understanding Your Carbon Footprint: A Beginner's Guide",
    excerpt:
      "Every action we take leaves a carbon trace. From the food we eat to the way we commute, understanding where your emissions come from is the first step to reducing them.",
    content: `
## What Is a Carbon Footprint?

A carbon footprint is the total amount of greenhouse gases — primarily carbon dioxide (CO₂) and methane — generated by our actions. It's measured in kilograms or tonnes of CO₂-equivalent (CO₂e).

The average Indian generates approximately **1.9 tonnes of CO₂** per year, compared to the global average of **4.7 tonnes**. While India's per-capita footprint is lower, urban lifestyles are pushing individual numbers higher.

## The Four Big Buckets

### 1. Travel
Transportation accounts for roughly **29%** of global greenhouse gas emissions. A single long-haul flight can generate more CO₂ than a month of daily commutes. Switching to public transit just twice a week can save **~150 kg CO₂** per year.

### 2. Food
What's on your plate matters enormously. Beef production generates **27 kg CO₂e per kg** of meat, while lentils produce less than **1 kg CO₂e per kg**. Replacing one beef meal per week with a plant-based option saves roughly **500 kg CO₂** annually.

### 3. Energy
Home energy use — air conditioning, heating, appliances, and lighting — typically contributes **20–25%** of a household's footprint. Switching to LED bulbs alone can cut lighting emissions by up to **80%**.

### 4. Shopping & Consumption
Fast fashion, electronics, and single-use plastics all carry embedded carbon costs from manufacturing and shipping. Buying secondhand or repairing items instead of replacing them can significantly reduce this bucket.

## Why Tracking Matters

You can't manage what you don't measure. Regular tracking helps you:
- Identify your highest-impact habits
- Set realistic reduction targets
- Celebrate genuine progress
- Make informed trade-offs

Canopy makes this easy with one-tap activity logging and instant emissions calculations based on real emission factors.

## Start Small, Think Long-Term

Cutting your footprint by even **10%** in year one is meaningful. Combine a few high-impact changes — flying less, eating less meat twice a week, and switching to public transit — and you could save **1–2 tonnes CO₂** annually.

The planet doesn't need a handful of people living perfectly. It needs millions of people making better choices consistently. That's what Canopy is built for.
    `,
    author: { name: "Priya Sharma", role: "Sustainability Researcher", avatar: "PS" },
    category: "Education",
    readTime: 6,
    publishedAt: "2026-06-01",
    coverEmoji: "🌍",
    tags: ["carbon footprint", "beginner", "sustainability", "climate"],
  },
  {
    slug: "7-habits-to-reduce-emissions-this-week",
    title: "7 Habits That Can Meaningfully Reduce Your Emissions This Week",
    excerpt:
      "Small, consistent changes add up faster than you'd expect. Here are seven science-backed habits you can start today — no lifestyle overhaul required.",
    content: `
## Habit 1: Go Plant-Based Two Days a Week

You don't need to go vegan overnight. Research shows that adopting a plant-based diet just **two days a week** can reduce your food-related emissions by up to **30%**. Start with Monday and Wednesday — #MeatlessMonday is already a global movement.

**Savings: ~400 kg CO₂/year**

## Habit 2: Use Public Transit or Cycle for Short Trips

Trips under 5 km by car are the least fuel-efficient. Your engine is cold, traffic is dense, and emissions per km are at their peak. Swapping these trips for cycling or a bus reduces transport emissions significantly.

**Savings: ~200 kg CO₂/year**

## Habit 3: Unplug Devices on Standby

Electronics on standby consume **5–10% of your home's electricity**. Smart power strips or simply unplugging devices when not in use costs nothing and adds up over a year.

**Savings: ~50–100 kg CO₂/year**

## Habit 4: Reduce Shower Time by 2 Minutes

Hot water heating is one of the most energy-intensive household activities. Cutting your daily shower by just two minutes saves an estimated **50 kg CO₂/year** and about **15,000 liters of water**.

**Savings: ~50 kg CO₂/year**

## Habit 5: Buy Local and Seasonal Produce

Produce flown in from another continent can have a carbon footprint **50x higher** than locally grown equivalents. Check your local market for seasonal vegetables — they're fresher, cheaper, and lower-carbon.

**Savings: ~100 kg CO₂/year**

## Habit 6: Wash Clothes in Cold Water

Modern detergents work just as well in cold water, and **90% of the energy** used to wash clothes goes toward heating the water. Switch to a cold wash cycle by default.

**Savings: ~40 kg CO₂/year**

## Habit 7: Take One Less Flight Per Year

Aviation is one of the highest per-activity sources of CO₂. A round-trip flight from Mumbai to London generates approximately **1.5 tonnes CO₂** — nearly equal to the average Indian's annual footprint. Consider train travel for domestic trips, or video calls for business meetings.

**Savings: 500 kg – 2 tonnes CO₂/year**

---

Logging all of these in Canopy will unlock challenges, grow your ecosystem, and show you your real-time progress. Every habit tracked is a seed planted.
    `,
    author: { name: "Arjun Mehta", role: "Climate Action Coach", avatar: "AM" },
    category: "Lifestyle",
    readTime: 5,
    publishedAt: "2026-06-08",
    coverEmoji: "🌱",
    tags: ["habits", "lifestyle", "tips", "carbon reduction"],
  },
  {
    slug: "how-canopy-calculates-your-emissions",
    title: "How Canopy Calculates Your Emissions (And Why It Matters)",
    excerpt:
      "Not all carbon calculators are created equal. Here's exactly how Canopy converts your daily activities into kg CO₂ — with transparent, science-backed emission factors.",
    content: `
## The Problem with Vague Carbon Tools

Most carbon calculators ask you to estimate an annual total — "how many flights do you take?" — and return a number with no context. They're useful for awareness but not for behavior change.

Canopy works differently. We calculate emissions **per activity, in real time**, using granular emission factors drawn from peer-reviewed sources including IPCC AR6, DEFRA emission factors, and ECOINVENT lifecycle data.

## The Formula

Every activity log produces an emissions estimate using:

\`\`\`
Emissions (kg CO₂e) = Activity Quantity × Emission Factor × Mode Modifier
\`\`\`

For example, a 15 km car journey in a petrol car:
- Activity: 15 km travel
- Emission factor: 0.192 kg CO₂e / km (petrol car)
- Mode modifier: 1.0 (solo driver)
- **Result: 2.88 kg CO₂e**

The same journey by electric train:
- Emission factor: 0.041 kg CO₂e / km
- **Result: 0.62 kg CO₂e** — **77% less**

## Categories We Cover

| Category | Examples |
|----------|----------|
| **Travel** | Car, bus, train, metro, flight, bike |
| **Food** | Beef, chicken, dairy, vegetables, processed foods |
| **Energy** | Electricity, natural gas, LPG, AC usage |
| **Shopping** | Clothing, electronics, furniture, packaging |

## The Canopy Score

Your Canopy Score (0–100) is calculated weekly:
- **90–100**: Exceptionally low impact
- **70–89**: Below Indian average — great work
- **50–69**: Near average — room to improve
- **Below 50**: Above average — focus on your top buckets

The score feeds into your ecosystem visualization — more on that in the next post.

## Why Transparency Matters

We publish our emission factors in the open-source repository. If you think a factor is wrong or outdated, open an issue. Carbon science evolves, and so should our numbers.

The goal isn't precision to five decimal places — it's helping you understand the **relative impact** of your choices, so you make better ones more often.
    `,
    author: { name: "Devika Nair", role: "Data Scientist, Canopy", avatar: "DN" },
    category: "Behind the Scenes",
    readTime: 7,
    publishedAt: "2026-06-14",
    coverEmoji: "📊",
    tags: ["carbon calculation", "science", "emission factors", "transparency"],
  },
  {
    slug: "india-climate-action-urban-guide",
    title: "Urban India's Climate Moment: What You Can Do Right Now",
    excerpt:
      "India is on the front lines of climate change and also one of its fastest-growing emitters. Urban Indians have unique leverage — here's how to use it.",
    content: `
## India's Dual Reality

India is both one of the most climate-vulnerable nations and one of the fastest-growing carbon emitters. With over **600 million urban residents** expected by 2030, the choices made by India's cities will shape global climate outcomes.

The good news: India's per-capita footprint is still well below global averages. But urban lifestyles — AC-cooled offices, car commutes, and meat-heavy diets — are pushing individual numbers upward.

## The Urban Opportunity

Urban Indians have access to options that rural populations don't:
- **Metro and bus rapid transit systems** in 20+ cities
- **EV charging infrastructure** expanding rapidly
- **Plant-based and local food markets** in every major city
- **Solar panel leasing programs** from state electricity boards

## Where Urban Emissions Come From

A typical urban professional in India generates around **3–5 tonnes CO₂/year**:

| Source | Share |
|--------|-------|
| Home energy (AC, appliances) | ~35% |
| Personal transport | ~30% |
| Food | ~20% |
| Shopping & consumption | ~15% |

## Three High-Impact Moves for Urban Indians

### 1. Switch to an EV or Use Metro
The Delhi Metro alone has **offset over 6 million tonnes of CO₂** since 2002. If you're buying a new vehicle, the EV total cost of ownership now rivals petrol in most Indian states.

### 2. Solar on Your Rooftop or Society
Net metering policies in most states allow excess solar to be sold back to the grid. A 3kW system in a sunny city generates enough electricity to cover a 2BHK apartment — and typically pays back in 4–6 years.

### 3. Reduce AC Dependency with Passive Cooling
Setting your AC to **24°C instead of 18°C** saves approximately **6–8% electricity per degree**. Adding ceiling fans and thermal curtains can make 26–27°C comfortable enough to reduce AC hours significantly.

## Your Voice Matters

Beyond personal action, urban Indians can push for:
- Better cycling infrastructure from local municipalities
- EV mandates for city bus fleets  
- Green building standards in new residential projects

Canopy helps you track the personal side. But don't stop there — climate action at scale requires both individual and collective effort.
    `,
    author: { name: "Rohit Kapoor", role: "Urban Sustainability Consultant", avatar: "RK" },
    category: "India Focus",
    readTime: 8,
    publishedAt: "2026-06-19",
    coverEmoji: "🏙️",
    tags: ["india", "urban", "climate", "action", "sustainability"],
  },
  {
    slug: "canopy-ecosystem-explainer",
    title: "The Living Ecosystem: How Your Choices Grow a Virtual Forest",
    excerpt:
      "Canopy's ecosystem visualization isn't just a pretty animation — it's a real-time reflection of your climate impact. Here's how it works.",
    content: `
## Why a Visual Ecosystem?

Behavior change research consistently shows that **tangible, emotional feedback** is more effective than numbers alone. Seeing a thriving forest grow because of your choices activates reward pathways that a graph simply cannot.

Canopy's ecosystem is a living, breathing metaphor for your climate impact. It evolves daily based on your actual behavior data.

## How the Ecosystem Responds to Your Data

Your ecosystem state is calculated from a composite input including:
- Your **Canopy Score** (weekly emissions vs. Indian average)
- Your **streak** (consecutive days with logged activity)
- **Completed challenges** count
- **Total activity logs** — more data means a richer visualization

### The Five Ecosystem Stages

| Stage | Canopy Score | Description |
|-------|-------------|-------------|
| 🌱 Seedling | < 30 | A small sapling just taking root |
| 🌿 Sprouting | 30–49 | Young growth with first leaves |
| 🌳 Canopy | 50–69 | A maturing tree with spreading branches |
| 🌲 Thriving | 70–84 | A lush, diverse ecosystem |
| 🌏 Guardian | 85–100 | A full forest ecosystem, teeming with life |

## What the Animals Mean

Each creature that appears in your ecosystem represents a milestone:
- **Butterflies** appear when you complete your first challenge
- **Birds** arrive when your streak reaches 7+ days  
- **Fireflies** light up when your Canopy Score crosses 70
- **Flowers** bloom with each 10% reduction in weekly emissions

## The Emotional Design Philosophy

We intentionally made the ecosystem feel alive — leaves sway, birds move, sunlight filters through branches. The goal is to make environmental stewardship feel like **nurturing something precious**, not like doing homework.

When you miss a day of logging, the ecosystem doesn't die — it gently fades, like a plant that needs water. This is intentional. Climate action isn't about perfection; it's about consistency over time.

## Future: Shared Ecosystems

We're building a feature where friend groups or households can contribute to a **shared ecosystem**. Your individual actions combine to grow a communal forest — visible to everyone in the group.

For now, your ecosystem is yours. Tend to it daily, and watch what grows.
    `,
    author: { name: "Meera Iyer", role: "Product Designer, Canopy", avatar: "MI" },
    category: "Product",
    readTime: 5,
    publishedAt: "2026-06-21",
    coverEmoji: "🌲",
    tags: ["ecosystem", "product", "design", "gamification", "behavior change"],
  },
  {
    slug: "ai-coach-behind-the-scenes",
    title: "Meet Your AI Coach: How Gemini Powers Personalized Climate Guidance",
    excerpt:
      "Canopy's AI Coach is built on Google's Gemini model and trained on your personal carbon data to give genuinely useful, actionable advice — not generic platitudes.",
    content: `
## Why Generic Advice Fails

"Eat less meat." "Take shorter showers." "Use public transport."

We've all heard these tips hundreds of times. They don't work — not because they're wrong, but because they're not *yours*. Generic advice doesn't know that you travel 80 km daily for work, or that you already eat plant-based four days a week.

Canopy's AI Coach knows all of this. And that changes everything.

## Powered by Gemini

Canopy's coach is built on **Google Gemini**, one of the most capable large language models available. But raw language capability isn't what makes it useful — the magic is in the context we provide.

Before every coach response, we assemble a **rich personal context** including:
- Your last 90 days of activity logs
- Your top emission categories this week vs. last
- Your active and completed challenges
- Your streak and consistency metrics
- Your ecosystem stage

The coach receives this as structured context, and responds specifically to *your* situation.

## What the Coach Can Do

### Personalized Reduction Tips
Not "eat less meat" — but "You've logged beef 4 times this week (5.2 kg CO₂). Swapping one for lentils would save ~1.3 kg and bring you below your weekly target."

### Challenge Guidance
"You're 70% through the Public Transit challenge. You need 2 more trips by Sunday — here are three convenient metro routes near your logged locations."

### Progress Celebration
"You've reduced travel emissions by 22% vs. last month. That's the equivalent of planting 3 trees. Your ecosystem agrees — check your new bird visitor!"

### Honest Accountability
"Your energy emissions spiked this week — likely AC use in the heatwave. That's understandable. Here's how to offset it with one easy switch..."

## Privacy First

Your activity data never leaves Canopy's systems for training purposes. It's used only to generate your specific coaching responses and is never shared or sold.

The coach gets smarter as the underlying Gemini model improves — but your data stays private.

## Try It

Open the AI Coach panel, type anything — "What should I focus on this week?" or "How am I doing?" — and watch it give you an answer that actually knows who you are.

That's the promise: a coach that feels like it genuinely cares about *your* progress.
    `,
    author: { name: "Arjun Mehta", role: "Climate Action Coach", avatar: "AM" },
    category: "Technology",
    readTime: 6,
    publishedAt: "2026-06-21",
    coverEmoji: "🤖",
    tags: ["AI", "Gemini", "personalization", "coach", "technology"],
  },
]

export function getBlogPost(slug: string): BlogPost | undefined {
  return BLOG_POSTS.find((p) => p.slug === slug)
}

export function getBlogPostsByCategory(category: string): BlogPost[] {
  return BLOG_POSTS.filter((p) => p.category === category)
}

export const BLOG_CATEGORIES = [...new Set(BLOG_POSTS.map((p) => p.category))]
